### ISSUE TITLE
EPG local XML input failure.

### ISSUE THREAD

**Issue by jobrien2001** [jjssoftware/m3u-epg-editor#19]
Input for m3u seems ot be working fine in the format -m=file:///home/.hts/test.m3u

Input for EPG thows errors in the format -e=file:///home/hts/m3u/test.xml

I have tried different xml files to exclude errors.  It will take gz compressed files but no the xml.  

On of the reasons to use local files is to prepare the xml before the script is run.  I could pack the XML before running the script but then the script would unpack it, but that seems like a waste of CPU and IO.

```
2019-01-04T21:48:00.971372 Traceback (most recent call last):
  File "./m3u/m3u-epg-editor.py", line 670, in <module>
    main()
  File "./m3u/m3u-epg-editor.py", line 159, in main
    epg_filename = load_epg(args)
  File "./m3u/m3u-epg-editor.py", line 515, in load_epg
    epg_filename = save_original_epg(is_gzipped, args.outdirectory, epg_response)
  File "./m3u/m3u-epg-editor.py", line 546, in save_original_epg
    epg_response.raw.decode_content = True
AttributeError: 'file' object has no attribute 'decode_content'

2019-01-04T21:48:00.971454 process terminated early due to an exception
2019-01-04T21:48:00.971495 process completed```

**Comment by jjssoftware** [comment]
Thanks, interesting..potentially a bug. I'll take a look.

**Comment by jjssoftware** [comment]
It looks like it was a bug, I've applied https://github.com/jjssoftware/m3u-epg-editor/commit/9ea5431d8a69c25f9323b1ec3bf62d5262244526 as the fix.

Please give the latest a try. Feel free to reopen this if it's not sorted, thanks.
